create table public.listing_zones (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  kind text not null default 'floor' check (kind in ('floor', 'outdoor', 'structure', 'amenity')),
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now()
);

create unique index listing_zones_listing_name_idx on public.listing_zones (listing_id, lower(name));
create index listing_zones_listing_order_idx on public.listing_zones (listing_id, sort_order, id);

alter table public.listing_photos
  add column zone_id bigint references public.listing_zones(id) on delete set null;

create index listing_photos_zone_order_idx on public.listing_photos (zone_id, sort_order) where zone_id is not null;

insert into public.listing_zones (listing_id, name, kind, sort_order)
select distinct
  listing_id,
  case
    when room_type in ('Exterior', 'Outdoor') then 'Exterior'
    when room_type in ('Bedroom', 'Primary bedroom', 'Bathroom', 'Office') then 'Floor two'
    else 'Floor one'
  end,
  case when room_type in ('Exterior', 'Outdoor') then 'outdoor' else 'floor' end,
  case
    when room_type in ('Exterior', 'Outdoor') then 0
    when room_type in ('Bedroom', 'Primary bedroom', 'Bathroom', 'Office') then 2
    else 1
  end
from public.listing_photos
where room_type is not null and room_type <> 'Unsorted';

update public.listing_photos photo
set zone_id = zone.id
from public.listing_zones zone
where zone.listing_id = photo.listing_id
  and zone.name = case
    when photo.room_type in ('Exterior', 'Outdoor') then 'Exterior'
    when photo.room_type in ('Bedroom', 'Primary bedroom', 'Bathroom', 'Office') then 'Floor two'
    else 'Floor one'
  end
  and photo.room_type is not null
  and photo.room_type <> 'Unsorted';

alter table public.listing_zones enable row level security;

create policy listing_zones_select_member on public.listing_zones
for select to authenticated
using (exists (
  select 1 from public.listings listing
  where listing.id = listing_id
    and (select private.is_workspace_member(listing.workspace_id))
));

create policy listing_zones_insert_member on public.listing_zones
for insert to authenticated
with check (exists (
  select 1 from public.listings listing
  where listing.id = listing_id
    and (select private.is_workspace_member(listing.workspace_id))
));

create policy listing_zones_update_member on public.listing_zones
for update to authenticated
using (exists (
  select 1 from public.listings listing
  where listing.id = listing_id
    and (select private.is_workspace_member(listing.workspace_id))
))
with check (exists (
  select 1 from public.listings listing
  where listing.id = listing_id
    and (select private.is_workspace_member(listing.workspace_id))
));

create policy listing_zones_delete_member on public.listing_zones
for delete to authenticated
using (exists (
  select 1 from public.listings listing
  where listing.id = listing_id
    and (select private.is_workspace_member(listing.workspace_id))
));

grant select, insert, update, delete on public.listing_zones to authenticated;
grant usage, select on sequence public.listing_zones_id_seq to authenticated;
